
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:5 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/zfogg/.local/share/asdf/plugins/nodejs/shims/"
      - "/Users/zfogg/.local/share/asdf/installs/nodejs/25.4.0/bin/"
      - "/Users/zfogg/.bun/bin/"
      - "/Users/zfogg/.gem/bin/"
      - "/opt/homebrew/opt/ruby/bin/"
      - "/Users/zfogg/.local/share/pnpm/"
      - "/Users/zfogg/bin/"
      - "/Users/zfogg/.local/bin/"
      - "/Users/zfogg/.cabal/bin/"
      - "/Users/zfogg/.cargo/bin/"
      - "/Users/zfogg/.local/share/asdf/shims/"
      - "/Users/zfogg/src/go/bin/"
      - "/opt/homebrew/opt/ccache/libexec/"
      - "/opt/homebrew/opt/findutils/libexec/gnubin/"
      - "/opt/homebrew/opt/coreutils/libexec/gnubin/"
      - "/opt/homebrew/opt/libtool/libexec/gnubin/"
      - "/opt/homebrew/opt/make/libexec/gnubin/"
      - "/opt/homebrew/opt/grep/libexec/gnubin/"
      - "/opt/homebrew/opt/ed/libexec/gnubin/"
      - "/opt/homebrew/opt/gawk/libexec/gnubin/"
      - "/opt/homebrew/opt/gnu-sed/libexec/gnubin/"
      - "/opt/homebrew/opt/gnu-tar/libexec/gnubin/"
      - "/opt/homebrew/opt/gnu-which/libexec/gnubin/"
      - "/opt/homebrew/opt/gnu-indent/libexec/gnubin/"
      - "/opt/homebrew/opt/curl/bin/"
      - "/opt/homebrew/opt/gnu-getopt/bin/"
      - "/opt/homebrew/opt/file-formula/bin/"
      - "/opt/homebrew/opt/unzip/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/Library/Developer/CommandLineTools/usr/bin/"
      - "/Applications/kitty.app/Contents/MacOS/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Users/zfogg/.local/share/nvim/lazy/fzf/bin/"
    searched_directories:
      - "/Users/zfogg/.local/share/asdf/plugins/nodejs/shims/uname"
      - "/Users/zfogg/.local/share/asdf/installs/nodejs/25.4.0/bin/uname"
      - "/Users/zfogg/.bun/bin/uname"
      - "/Users/zfogg/.gem/bin/uname"
      - "/opt/homebrew/opt/ruby/bin/uname"
      - "/Users/zfogg/.local/share/pnpm/uname"
      - "/Users/zfogg/bin/uname"
      - "/Users/zfogg/.local/bin/uname"
      - "/Users/zfogg/.cabal/bin/uname"
      - "/Users/zfogg/.cargo/bin/uname"
      - "/Users/zfogg/.local/share/asdf/shims/uname"
      - "/Users/zfogg/src/go/bin/uname"
      - "/opt/homebrew/opt/ccache/libexec/uname"
      - "/opt/homebrew/opt/findutils/libexec/gnubin/uname"
    found: "/opt/homebrew/opt/coreutils/libexec/gnubin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/zfogg/.local/share/asdf/plugins/nodejs/shims"
        - "/Users/zfogg/.local/share/asdf/installs/nodejs/25.4.0/bin"
        - "/Users/zfogg/.bun/bin"
        - "/Users/zfogg/.gem/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/zfogg/.local/share/pnpm"
        - "/Users/zfogg/bin"
        - "/Users/zfogg/.local/bin"
        - "/Users/zfogg/.cabal/bin"
        - "/Users/zfogg/.cargo/bin"
        - "/Users/zfogg/.local/share/asdf/shims"
        - "/Users/zfogg/src/go/bin"
        - "/opt/homebrew/opt/ccache/libexec"
        - "/opt/homebrew/opt/findutils/libexec/gnubin"
        - "/opt/homebrew/opt/coreutils/libexec/gnubin"
        - "/opt/homebrew/opt/libtool/libexec/gnubin"
        - "/opt/homebrew/opt/make/libexec/gnubin"
        - "/opt/homebrew/opt/grep/libexec/gnubin"
        - "/opt/homebrew/opt/ed/libexec/gnubin"
        - "/opt/homebrew/opt/gawk/libexec/gnubin"
        - "/opt/homebrew/opt/gnu-sed/libexec/gnubin"
        - "/opt/homebrew/opt/gnu-tar/libexec/gnubin"
        - "/opt/homebrew/opt/gnu-which/libexec/gnubin"
        - "/opt/homebrew/opt/gnu-indent/libexec/gnubin"
        - "/opt/homebrew/opt/curl/bin"
        - "/opt/homebrew/opt/gnu-getopt/bin"
        - "/opt/homebrew/opt/file-formula/bin"
        - "/opt/homebrew/opt/unzip/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/Library/Developer/CommandLineTools/usr/bin"
        - "/Applications/kitty.app/Contents/MacOS"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/Users/zfogg/.local/share/nvim/lazy/fzf/bin"
...
